duoMessages:
  - "是我，拽姐。3 天没学日语了，你是想怎样？……算了，懒得管你。退订请回 TD"
  - "S 屬性要爆發 (Study)"
  - "加油！学语言最重要的就是坚持。每天学习，积少成多！千万不要轻易放弃立下的目标哦！"
duoDamagedMessages:
  - "Spanish or Vanish"
  - "French or Trench"
  - "Japanese or I break your knees"
  - "German or vermin"